rules/urls.py
"""
Copyright(C) 2014-2018, Stamus Networks
Written by Eric Leblond <eleblond@stamus-networks.com>

This file is part of Scirius.

Scirius is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Scirius is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Scirius.  If not, see <http://www.gnu.org/licenses/>.
"""


from django.conf.urls import url

from rules import views

urlpatterns = [
    url(r'^$', views.index, name='rules_index'),
    url(r'^search$', views.search, name='scirius_search'),
    url(r'^es$', views.elasticsearch, name='elasticsearch'),
    url(r'^settings/$', views.system_settings, name='system_settings'),
    url(r'^source/$', views.sources, name='sources'),
    url(r'^source/add$', views.add_source, name='add_source'),
    url(r'^source/add_public$', views.add_public_source, name='add_public_source'),
    url(r'^source/update_public$', views.update_public_sources, name='update_public_sources'),
    url(r'^source/(?P<source_id>\d+)/$', views.source, name='source'),
    url(r'^source/(?P<source_id>\d+)/update$', views.update_source, name='update_source'),
    url(r'^source/(?P<source_id>\d+)/diff$', views.diff_source, name='diff_source'),
    url(r'^source/(?P<source_id>\d+)/changelog', views.changelog_source, name='changelog_source'),
    url(r'^source/(?P<source_id>\d+)/edit$', views.edit_source, name='edit_source'),
    url(r'^source/(?P<source_id>\d+)/delete$', views.delete_source, name='delete_source'),
    url(r'^source/(?P<source_id>\d+)/activate/(?P<ruleset_id>\d+)$', views. activate_source, name='activate_source'),
    url(r'^source/(?P<source_id>\d+)/test$', views.test_source, name='test_source'),
    url(r'^sourceupdate/(?P<update_id>\d+)$', views.sourceupdate, name='sourceupdate'),
    url(r'^category/$', views.categories, name='categories'),
    url(r'^category/(?P<cat_id>\d+)/$', views.category, name='category'),
    url(r'^category/(?P<cat_id>\d+)/disable$', views.disable_category, name='disable_category'),
    url(r'^category/(?P<cat_id>\d+)/enable$', views.enable_category, name='enable_category'),
    url(r'^category/(?P<cat_id>\d+)/transform$', views.transform_category, name='transform_category'),
    url(r'^ruleset/$', views.rulesets, name='rulesets'),
    url(r'^ruleset/add$', views.add_ruleset, name='add_ruleset'),
    url(r'^ruleset/(?P<ruleset_id>\d+)/$', views.ruleset, name='ruleset'),
    url(r'^ruleset/(?P<ruleset_id>\d+)/update$', views.update_ruleset, name='update_ruleset'),
    url(r'^ruleset/(?P<ruleset_id>\d+)/edit$', views.edit_ruleset, name='edit_ruleset'),
    url(r'^ruleset/(?P<ruleset_id>\d+)/delete$', views.delete_ruleset, name='delete_ruleset'),
    url(r'^ruleset/(?P<ruleset_id>\d+)/addsupprule$', views.ruleset_add_supprule, name='addsupprule'),
    url(r'^ruleset/(?P<ruleset_id>\d+)/display$', views.ruleset, {'mode': 'display'}, name='display_ruleset'),
    url(r'^ruleset/(?P<ruleset_id>\d+)/export$', views.ruleset, {'mode': 'export'}, name='export_ruleset'),
    url(r'^ruleset/(?P<ruleset_id>\d+)/copy$', views.copy_ruleset, name='copy_ruleset'),
    url(r'^ruleset/(?P<ruleset_id>\d+)/changelog', views.changelog_ruleset, name='changelog_ruleset'),
    url(r'^ruleset/(?P<ruleset_id>\d+)/test', views.test_ruleset, name='test_ruleset'),
    url(r'^rule/(?P<rule_id>\d+)/disable$', views.disable_rule, name='disable_rule'),
    url(r'^rule/(?P<rule_id>\d+)/enable$', views.enable_rule, name='enable_rule'),
    url(r'^rule/(?P<rule_id>\d+)/delete$', views.delete_alerts, name='delete_alerts'),
    url(r'^rule/(?P<rule_id>\d+)/availability$', views.toggle_availability, name='toggle_availability'),
    url(r'^rule/(?P<rule_id>\d+)/edit$', views.edit_rule, name='edit_rule'),
    url(r'^rule/(?P<rule_id>\d+)/threshold$', views.threshold_rule, name='threshold_rule'),
    url(r'^rule/(?P<rule_id>\d+)/comment$', views.comment_rule, name='comment_rule'),
    url(r'^rule/pk/(?P<rule_id>\d+)/$', views.rule, {'key': 'pk'}, name='rule'),
    url(r'^rule/(?P<rule_id>\d+)/$', views.rule, {'key': 'sid'}, name='rule_sid'),
    url(r'^rule/pk/(?P<rule_id>\d+)/test/(?P<ruleset_id>\d+)$', views.test_rule, {'key': 'pk'}, name='test_rule'),
    url(r'^info$', views.info, name='info'),
    url(r'^threshold/(?P<threshold_id>\d+)/$', views.threshold, name='threshold'),
    url(r'^threshold/(?P<threshold_id>\d+)/delete$', views.delete_threshold, name='delete_threshold'),
    url(r'^threshold/(?P<threshold_id>\d+)/edit$', views.edit_threshold, name='edit_threshold'),
    url(r'^history$', views.history, name='history'),
    url(r'^comment$', views.history, name='comment'),
    url(r'^policies$', views.policies, name='policies'),
    url(r'^hunt$', views.hunt, name='hunt'),
]

scirius/urls.py
from django.conf.urls import url, include
from django.conf import settings

from .views import homepage, KibanaProxyView, EveboxProxyView, MolochProxyView, static_redirect, ui_view
from .rest_api import router

urlpatterns = [
    url(r'^rules/', include('rules.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^viz/', include('viz.urls')),
    url(r'^' + settings.RULESET_MIDDLEWARE + '/', include('' + settings.RULESET_MIDDLEWARE + '.urls')),
    url(r'^rest/', include(router.urls)),
    url(r'^stamus(/.*)?$', ui_view),
    url('^$', homepage),
    # Forward "app/kibana.*" to kibana (work around to https://github.com/elastic/kibana/issues/5230)
    url(r'^(?P<path>app/.*)$', KibanaProxyView.as_view()),
    url(r'^(?P<path>status.*)$', KibanaProxyView.as_view()),
    url(r'^(?P<path>api.*)$', KibanaProxyView.as_view()),
    url(r'^(?P<path>plugins.*)$', KibanaProxyView.as_view()),
    # Forward timelion plugin
    url(r'^(?P<path>timelion/.*)$', KibanaProxyView.as_view()),
    url(r'^(?P<path>bundles/.*)$', KibanaProxyView.as_view()),
    url(r'^(?P<path>elasticsearch/.*)$', KibanaProxyView.as_view()),
    url(r'^kibana/(?P<path>.*)$', KibanaProxyView.as_view()),
    url(r'^evebox/(?P<path>.*)$', EveboxProxyView.as_view()),
    # Kibana 5.2 specific
    url(r'^(?P<path>ui/fonts.*)$', KibanaProxyView.as_view()),
    url(r'^(?P<path>es_admin.*)$', KibanaProxyView.as_view()),

    # Moloch proxy
    url(r'^moloch/(?P<path>.*)$', MolochProxyView.as_view()),
]

if settings.STATIC_AUTHENTICATED:
    urlpatterns += [
        url(r'^static/(?P<static_path>.*)$', static_redirect, name='static_redirect'),
    ]

viz/urls.py
"""
Copyright(C) 2018, Stamus Networks
Written by Eric Leblond <eleblond@stamus-networks.com>

This file is part of Scirius.

Scirius is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Scirius is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Scirius.  If not, see <http://www.gnu.org/licenses/>.
"""

from __future__ import unicode_literals
from django.conf.urls import url

from viz import views

urlpatterns = [
    url(r'^dashboard$', views.dashboard, name='viz_dashboard'),
    url(r'^dashboard_target$', views.dashboard_target, name='viz_target_dashboard'),
]

rules/forms.py
"""
Copyright(C) 2014, Stamus Networks
Written by Eric Leblond <eleblond@stamus-networks.com>

This file is part of Scirius.

Scirius is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Scirius is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Scirius.  If not, see <http://www.gnu.org/licenses/>.
"""


import tarfile
import json
from io import BytesIO
from django import forms
from django.core.exceptions import NON_FIELD_ERRORS, PermissionDenied
from django.core.serializers.json import DjangoJSONEncoder
from django.db.models import F
from django.db import transaction
from rules.models import (
    Ruleset, Source, Category, SourceAtVersion, SystemSettings, Threshold, Transformation,
    RuleProcessingFilter, RuleProcessingFilterDef, FilterSet
)


class RulesetPolicyEditPermForm:
    WRITE_PERM = 'rules.ruleset_policy_edit'


class ConfigurationEditPermForm:
    WRITE_PERM = 'rules.configuration_edit'


class CommentForm(forms.Form):
    comment = forms.CharField(widget=forms.Textarea, label="Optional comment", required=False)

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)

        # Put the comment field at the end of the self.fields ordered dict
        comment = self.fields.pop('comment')
        self.fields['comment'] = comment


class RulesetChoiceForm(CommentForm):
    rulesets = forms.ModelMultipleChoiceField(None, widget=forms.CheckboxSelectMultiple(), required=True)

    def __init__(self, *args, **kwargs):
        super(RulesetChoiceForm, self).__init__(*args, **kwargs)
        ruleset_list = Ruleset.objects.all()
        self.fields['rulesets'].queryset = ruleset_list

        if hasattr(self, 'rulesets_label'):
            self.fields['rulesets'].label = self.rulesets_label

        if not len(ruleset_list):
            if not (isinstance(self, AddSourceForm) or isinstance(self, AddPublicSourceForm)):
                self.errors[NON_FIELD_ERRORS] = ['Please create a ruleset first']
            self.fields.pop('rulesets')


class BaseEditForm:
    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request')
        super().__init__(*args, **kwargs)

        self.can_edit = request.user.has_perm(self.WRITE_PERM)
        if not self.can_edit:
            for key in self.fields.keys():
                self.fields[key].disabled = True

    def clean(self):
        if not self.can_edit:
            raise PermissionDenied()

        return super().clean()


class SystemSettingsForm(ConfigurationEditPermForm, BaseEditForm, forms.ModelForm, CommentForm):
    use_http_proxy = forms.BooleanField(label='Use a proxy', required=False)
    custom_elasticsearch = forms.BooleanField(label='Use a custom Elasticsearch server', required=False)
    http_proxy = forms.CharField(max_length=200, required=False, help_text='Proxy address of the form "http://username:password@hostname:port/"')
    elasticsearch_url = forms.CharField(max_length=200, empty_value='http://elasticsearch:9200/', required=False)
    use_proxy_for_es = forms.BooleanField(label='Use elasticsearch with system proxy', required=False)

    class Meta:
        model = SystemSettings
        exclude = []


class KibanaDataForm(forms.Form):
    file = forms.FileField(required=False)


class PoliciesForm(RulesetPolicyEditPermForm, BaseEditForm, forms.Form):
    file = forms.FileField(required=True)

    @staticmethod
    def _import(file_, delete):
        from scirius.utils import get_middleware_module

        with tarfile.open(fileobj=file_, mode='r:gz') as tar:
            policy = tar.getmember('policies.json')
            content = json.loads(tar.extractfile(policy).read().decode())

            with transaction.atomic():
                if delete:
                    removed_indexes = list(RuleProcessingFilter.objects.filter(imported=True).order_by('-index').values_list('index', flat=True))
                    RuleProcessingFilter.objects.filter(imported=True).delete()

                    for index in removed_indexes:
                        RuleProcessingFilter.objects.filter(index__gt=index).update(index=F('index') - 1)

                    FilterSet.objects.filter(user_id=None, imported=True).delete()
                    get_middleware_module('common').delete_policies()

                if len(content) > 0:
                    RuleProcessingFilter.objects.update(index=F('index') + len(content))

                for item in content:
                    extra_policies = get_middleware_module('common').extract_policies(item)

                    filter_defs_list = item.pop('filter_defs')
                    rulesets = item.pop('rulesets')

                    item['imported'] = True
                    filter_ = RuleProcessingFilter.objects.create(**item)
                    filter_.rulesets.set(Ruleset.objects.filter(name__in=rulesets))

                    for filter_defs in filter_defs_list:
                        filter_defs['proc_filter'] = filter_
                        filter_defs = RuleProcessingFilterDef.objects.create(**filter_defs)

                    if extra_policies:
                        extra_policies.update({'filter_': filter_})
                        get_middleware_module('common').import_policies(**extra_policies)

                filterset = tar.getmember('filtersets.json')
                content = json.loads(tar.extractfile(filterset).read().decode())

                for item in content:
                    item['imported'] = True
                    FilterSet.objects.get_or_create(**item)

    @staticmethod
    def _export():
        from scirius.utils import get_middleware_module

        filter_fields = [f.name for f in RuleProcessingFilter._meta.get_fields() if f.name not in ('id', 'ruleset')]
        filterdef_fields = [f.name for f in RuleProcessingFilterDef._meta.get_fields() if f.name not in ('id', 'proc_filter')]
        filterset_fields = [f.name for f in FilterSet._meta.get_fields() if f.name not in ('id', 'user')]

        res = []
        for proc_filter in RuleProcessingFilter.objects.values(*filter_fields):
            proc_filter['filter_defs'] = list(RuleProcessingFilterDef.objects.filter(pk=proc_filter['filter_defs']).values(*filterdef_fields))
            proc_filter['rulesets'] = list(Ruleset.objects.filter(pk=proc_filter['rulesets']).values_list('name', flat=True))

            get_middleware_module('common').update_policies(proc_filter)

            res.append(proc_filter)

        # Get only shared filtersets
        json_filtersets = json.dumps(list(FilterSet.objects.filter(user_id=None).values(*filterset_fields)))
        json_content = json.dumps(res, cls=DjangoJSONEncoder)

        tar_path_io = BytesIO()
        with tarfile.open(fileobj=tar_path_io, mode="w:gz") as tar:
            policy_info = tarfile.TarInfo('policies.json')
            policy_info.size = len(json_content)
            tar.addfile(policy_info, BytesIO(bytes(json_content, 'utf-8')))

            filtersets_info = tarfile.TarInfo('filtersets.json')
            filtersets_info.size = len(json_filtersets)
            tar.addfile(filtersets_info, BytesIO(bytes(json_filtersets, 'utf-8')))

        return tar_path_io


class SourceForm(forms.ModelForm, CommentForm):
    file = forms.FileField(required=False)
    authkey = forms.CharField(max_length=100,
                              label="Optional authorization key",
                              required=False,
                              widget=forms.PasswordInput(render_value=True))

    class Meta:
        model = Source
        exclude = ['created_date', 'updated_date', 'cats_count', 'rules_count', 'public_source', 'version']

    def __init__(self, *args, **kwargs):
        source = kwargs.get('instance', None)
        super(SourceForm, self).__init__(*args, **kwargs)

        from scirius.utils import get_middleware_module
        choices = get_middleware_module('common').update_source_content_type(Source.CONTENT_TYPE, source)
        self.fields['datatype'] = forms.ChoiceField(choices=choices)


class AddSourceForm(forms.ModelForm, RulesetChoiceForm):
    file = forms.FileField(required=False)
    authkey = forms.CharField(max_length=100, label="Optional authorization key", required=False)
    rulesets_label = "Add source to the following ruleset(s)"

    class Meta:
        model = Source
        exclude = ['created_date', 'updated_date', 'cats_count', 'rules_count', 'public_source', 'version']

    def __init__(self, *args, **kwargs):
        super(AddSourceForm, self).__init__(*args, **kwargs)
        if 'rulesets' in self.fields:
            self.fields['rulesets'].required = False

        from scirius.utils import get_middleware_module
        choices = get_middleware_module('common').update_source_content_type(Source.CONTENT_TYPE)
        self.fields['datatype'] = forms.ChoiceField(choices=choices)


class AddPublicSourceForm(forms.ModelForm, RulesetChoiceForm):
    source_id = forms.CharField(max_length=100)
    secret_code = forms.CharField(max_length=100, required=False)
    use_iprep = forms.BooleanField(required=False)

    class Meta:
        model = Source
        exclude = ['created_date', 'updated_date', 'cats_count', 'rules_count', 'method', 'datatype', 'version']

    def __init__(self, *args, **kwargs):
        super(AddPublicSourceForm, self).__init__(*args, **kwargs)
        if 'rulesets' in self.fields:
            self.fields['rulesets'].required = False


# Display choices of SourceAtVersion
class RulesetForm(CommentForm):

rules/templates/rules/copy_ruleset.html
{% extends "rules/base.html" %}
{% load bootstrap3 %}
{% block sidebar %}
    <div class="panel-heading">
        <h2 class="panel-title">Copy ruleset "{{ object.name }}"</h2>
    </div>
{% endblock sidebar %}
{% block content %}
    {% if form %}
        <form class="form"
              action="{% url 'copy_ruleset' object.id %}"
              method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input class="btn btn-primary" type="submit" value="Submit" />
        </form>
    {% endif %}
{% endblock content %}

rules/templates/rules/delete.html
{% extends "rules/base.html" %}
{% load bootstrap3 %}
{% block sidebar %}
    <div class="panel-heading">
        <h2 class="panel-title">Delete object</h2>
    </div>
{% endblock sidebar %}
{% block content %}
    <h2 class="title">Are you sure you want to delete object {{ object.name|default:object.pk }}?</h2>
    <form class="form" action={% url delfn object.id %} method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class="btn btn-primary" type="submit">
            <span class="glyphicon glyphicon-trash">Delete object</span>
        </button>
    </form>
{% endblock content %}

rules/templates/rules/disable_rule.html
{% extends "rules/base.html" %}
{% load bootstrap3 %}
{% block content %}
    {% if form %}
        {% if operation == 'disable' %}
            <h4>Disable rule {{ rule.sid }} from ruleset(s)</h4>
        {% else %}
            <h4>Enable rule {{ rule.sid }} in ruleset(s)</h4>
        {% endif %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-4">
                    {% for ruleset in rulesets %}
                        {% if ruleset.deps_rules|length %}
                            In ruleset <strong>{{ ruleset.name }}</strong>, this will also
                            {% if operation == 'disable' %}
                                disable
                            {% else %}
                                enable
                            {% endif %}
                            the following rules due to flowbits dependencies:
                            <ul>
                                {% for rule in ruleset.deps_rules %}
                                    <li>
                                        <a href="{% url 'rule' rule.pk %}">{{ rule.msg }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    {% endfor %}
                    <form class="form" action={% if operation == 'disable' %}"{% url 'disable_rule' rule.sid %}"{% else %}"{% url 'enable_rule' rule.sid %}"{% endif %} method="post">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        {% buttons %}
                            <button type="submit" class="btn btn-primary">
                                {% if operation == 'disable' %}
                                    {% bootstrap_icon "ok" %} Disable
                                {% else %}
                                    {% bootstrap_icon "ok" %} Enable
                                {% endif %}
                            </button>
                        {% endbuttons %}
                    </form>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock content %}
{% block sidebar %}
    <div class="panel-heading">
        <h2 class="panel-title">Rule {{ rule.sid }}</h2>
    </div>
    <div class="panel-body">
        <ul class="action">
            {% if rule.state %}
                <li>
                    <a href="{% url 'edit_rule' rule.sid %}">Transform rule</a>
                </li>
                <li>
                    <a href="{% url 'disable_rule' rule.sid %}">Disable rule</a>
                </li>
                <li>
                    <a href="{% url 'enable_rule' rule.sid %}">Enable rule</a>
                </li>
                <li>
                    <a href="{% url 'threshold_rule' rule.sid %}?action=threshold">Threshold rule</a>
                </li>
                <li>
                    <a href="{% url 'threshold_rule' rule.sid %}?action=suppress">Suppress rule</a>
                </li>
            {% endif %}
            {# rule.state #}
        </ul>
    </div>
{% endblock sidebar %}

rules/templates/rules/hunt.html
{% load get_files from webpack_loader %}
{% load staticfiles %}
<!DOCTYPE html>
<html class="layout-pf layout-pf-fixed transitions" lang="en-us">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width" />
        <link rel="shortcut icon" href="{% static 'rules/favicon.ico' %}" />
        <title>Stamus - Hunt</title>
    </head>
    <body class="cards-pf">
        <div id="root"></div>
        <script type="text/javascript"
                src="{{ current_user_url }}"
                nonce="{{ request.csp_nonce }}"></script>
        {% get_files 'main' 'css' as css_files %}
        {% for css_file in css_files %}<link type="text/css" href="{{ css_file.url }}" rel="preload stylesheet" />{% endfor %}
        {% get_files 'main' 'js' as js_files %}
        {% for js_file in js_files %}
            <script type="text/javascript"
                    src="{{ js_file.url }}"
                    nonce="{{ request.csp_nonce }}"></script>
        {% endfor %}
        {% if settings.CUSTOM_CSS %}<link rel="stylesheet" type="text/css" href="{{ settings.CUSTOM_CSS }}" />{% endif %}
    </body>
</html>

rules/templates/rules/object_list.html
{% extends "rules/base.html" %}
{% block sidebar %}
    <div class="panel-heading">
        <h2 class="panel-title">{{ name }}</h2>
    </div>
    <ul class="panel-body">
        <li>{{ size }} object{{ size|pluralize }}</li>
    </ul>
    {% if manage_links %}
        <div class="panel-heading">
            <h2 class="panel-title">Manage {{ name }}</h2>
        </div>
        <ul class="panel-body">
            {% for url, title in manage_links.items  %}
                <li>
                    <a href="{% url url  %}">{{ title }}</a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
    <div class="panel-heading">
        <h2 class="panel-title">Action</h2>
    </div>
    {% if adduri %}
        <ul class="action panel-body">
            <li>
                <a href="{{ adduri }}">Add {{ action }}</a>
            </li>
            {% for url, title in action_links.items  %}
                <li>
                    <a href="{% url url  %}">{{ title }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <ul class="action panel-body">
            <li>
                <a href="{% url 'rules_index' %}{{ action }}/add">Add</a>
            </li>
        </ul>
    {% endif %}
{% endblock %}
{% block content %}
    {% if objects %}
        <div class="container-fluid">
            <div class="row">
                <h2 class="title">{{ action.title }}{{ objects|length|pluralize }}</h2>
                <div class="col-md-12">
                    {% load render_table from django_tables2 %}
                    {% render_table objects %}
                </div>
            </div>
        </div>
    {% else %}
        No object available.
    {% endif %}
{% endblock %}

rules/templates/rules/policies.html
{% extends "rules/base.html" %}
{% load bootstrap3  %}
{% block sidebar %}
    <div class="panel-heading">
        <h2 class="panel-title">Policies & Filter Sets</h2>
    </div>
    <ul class="panel-body">
        <li>Import to and export from Hunting</li>
    </ul>
{% endblock %}
{% block content %}
    <form class="form"
          enctype="multipart/form-data"
          action="{% url 'policies' %}"
          method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-5">
                <h2>Export Policies and custom Filter Sets from Hunting</h2>
                <p class="help-block">
                    Clicking on the button will download policies and filtersets.
                </p>
                {% buttons %}
                    <button type="submit" name="export" class="btn btn-primary">{% bootstrap_icon "download" %} Export</button>
                {% endbuttons %}
                {% if perms.rules.configuration_edit %}
                    <br>
                    <h2>Import Policies and custom Filter Sets to Hunting</h2>
                    <div class="form-group">
                        <label class="sr-only control-label" for="id_file">File</label>
                        <div class="row bootstrap3-multi-input" disabled="">
                            <div class="col-xs-12">
                                <p>
                                    <input type="file" name="file" class="" title="" id="id_file">
                                </p>
                                <input type="checkbox" id="delete_policies" name="delete">
                                <label for="delete_policies">Delete all previous imported policies and filtersets</label>
                                <br>
                                <p class="help-block" id="help-delete" style="display: none">
                                    <strong>WARNING:</strong>
                                    <a>Delete all previously imported policies and custom Filter Sets.</a><br>
                                    <a>All previously imported policies and custom filter sets will be deleted.</a>
                                </p>
                            </div>
                        </div>
                    </div>
                    {% buttons %}
                        <button type="submit" name="import" class="btn btn-warning">{% bootstrap_icon "upload" %} Import</button>
                    {% endbuttons %}
                {% endif %}
            </div>
        </div>
    </form>
    <script>
$(document).ready(function() {
    $("#delete_policies").click(function() {
        if ($("#delete_policies").is(":checked")) {
            $("#help-delete").show();
        } else {
            $("#help-delete").hide();
        }
    })
});
    </script>
{% endblock content %}

rules/templates/rules/search_rule.html
{% extends "rules/base.html" %}
{% load bootstrap3  %}
{% block sidebar %}
    <div class="panel-heading">
        <h2 class="panel-title">Action</h2>
    </div>
    <div class="panel-body">
        <form action="{% url 'addsupprule' ruleset.id %}" method="post">
            {% csrf_token %}
            <ul class="action">
                <li>
                    Search:
                    <input type="text" name="search" />
                </li>
            </ul>
        </form>
    </div>
{% endblock %}
{% block content %}
    <script language="JavaScript">
function tables2_toggle(source, name) {
    checkboxes = document.getElementsByName(name);
    for(var i in checkboxes)
        checkboxes[i].checked = source.checked;
}
    </script>
    {% if rules %}
        <h2 class="title">Rules</h2>
        {% load render_table from django_tables2 %}
        <form class="form"
              action="{% url 'addsupprule' ruleset.id %}"
              method="post">
            {% csrf_token %}
            {% render_table rules %}
            {% bootstrap_form form %}
            <input class="btn btn-primary"
                   type="submit"
                   value="Add selected rules to disabled rules list"/>
        </form>
    {% endif %}
{% endblock %}