accounts/urls.py
"""
Copyright(C) 2014, Stamus Networks
Written by Eric Leblond <eleblond@stamus-networks.com>

This file is part of Scirius.

Scirius is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Scirius is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Scirius.  If not, see <http://www.gnu.org/licenses/>.
"""


from django.conf.urls import url

from accounts import views

urlpatterns = [
    url(r'^$', views.list_accounts, name='list_accounts'),
    url(r'^logout/$', views.logoutview, name='accounts_logout'),
    url(r'^login/(?P<target>.*)$', views.loginview, name='accounts_login'),
    url(r'^user/$', views.list_users, name='list_users'),
    url(r'^user/add/$', views.add_user, name='add_user'),
    url(r'^user/(?P<user_id>\d+)$', views.edit_user, name='edit_user'),
    url(r'^user/(?P<user_id>\d+)/delete$', views.delete_user, name='delete_user'),
    url(r'^user/(?P<user_id>\d+)/edit_password$', views.edit_password, name='edit_password'),
    url(r'^role/$', views.list_groups, name='list_groups'),
    url(r'^role/add/$', views.add_group, name='add_group'),
    url(r'^role/(?P<group_id>\d+)$', views.edit_group, name='edit_group'),
    url(r'^role/(?P<group_id>\d+)/delete$', views.delete_group, name='delete_group'),
    url(r'^priorities/$', views.edit_priorities, name='edit_priorities'),
    url(r'^sort_priorities/$', views.sort_priorities, name='sort_priorities'),
    url(r'^current_user/$', views.current_user, name='current_user'),

    # TODO PERMS: split into different views
    url(r'^edit/(?P<action>.*)$', views.editview, name='accounts_edit'),
]

scirius/urls.py
from django.conf.urls import url, include
from django.conf import settings

from .views import homepage, KibanaProxyView, EveboxProxyView, MolochProxyView, static_redirect, ui_view
from .rest_api import router

urlpatterns = [
    url(r'^rules/', include('rules.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^viz/', include('viz.urls')),
    url(r'^' + settings.RULESET_MIDDLEWARE + '/', include('' + settings.RULESET_MIDDLEWARE + '.urls')),
    url(r'^rest/', include(router.urls)),
    url(r'^stamus(/.*)?$', ui_view),
    url('^$', homepage),
    # Forward "app/kibana.*" to kibana (work around to https://github.com/elastic/kibana/issues/5230)
    url(r'^(?P<path>app/.*)$', KibanaProxyView.as_view()),
    url(r'^(?P<path>status.*)$', KibanaProxyView.as_view()),
    url(r'^(?P<path>api.*)$', KibanaProxyView.as_view()),
    url(r'^(?P<path>plugins.*)$', KibanaProxyView.as_view()),
    # Forward timelion plugin
    url(r'^(?P<path>timelion/.*)$', KibanaProxyView.as_view()),
    url(r'^(?P<path>bundles/.*)$', KibanaProxyView.as_view()),
    url(r'^(?P<path>elasticsearch/.*)$', KibanaProxyView.as_view()),
    url(r'^kibana/(?P<path>.*)$', KibanaProxyView.as_view()),
    url(r'^evebox/(?P<path>.*)$', EveboxProxyView.as_view()),
    # Kibana 5.2 specific
    url(r'^(?P<path>ui/fonts.*)$', KibanaProxyView.as_view()),
    url(r'^(?P<path>es_admin.*)$', KibanaProxyView.as_view()),

    # Moloch proxy
    url(r'^moloch/(?P<path>.*)$', MolochProxyView.as_view()),
]

if settings.STATIC_AUTHENTICATED:
    urlpatterns += [
        url(r'^static/(?P<static_path>.*)$', static_redirect, name='static_redirect'),
    ]

viz/urls.py
"""
Copyright(C) 2018, Stamus Networks
Written by Eric Leblond <eleblond@stamus-networks.com>

This file is part of Scirius.

Scirius is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Scirius is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Scirius.  If not, see <http://www.gnu.org/licenses/>.
"""

from __future__ import unicode_literals
from django.conf.urls import url

from viz import views

urlpatterns = [
    url(r'^dashboard$', views.dashboard, name='viz_dashboard'),
    url(r'^dashboard_target$', views.dashboard_target, name='viz_target_dashboard'),
]

accounts/forms.py
"""
Copyright(C) 2014, Stamus Networks
Written by Eric Leblond <eleblond@stamus-networks.com>

This file is part of Scirius.

Scirius is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Scirius is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Scirius.  If not, see <http://www.gnu.org/licenses/>.
"""

from django import forms
from django.contrib.auth.models import User, Group as DjangoGroup
from django.contrib.auth.forms import PasswordChangeForm as DjangoPasswordChangeForm, UserCreationForm
from django.db.models import Max, F
import pytz

from .models import Group, SciriusUser

from scirius.utils import get_middleware_module
from rules.forms import CommentForm


class PasswordChangeForm(DjangoPasswordChangeForm):
    comment = forms.CharField(widget=forms.Textarea,
                              label="Optional comment",
                              required=False)

    def __init__(self, *args, **kwargs):
        super(PasswordChangeForm, self).__init__(*args, **kwargs)

        # Put the comment field at the end of the self.fields ordered dict
        comment = self.fields.pop('comment')
        self.fields['comment'] = comment


class GroupEditForm(forms.ModelForm, CommentForm):
    DEFAULT_GROUPS = ('Superuser', 'Staff', 'User')

    name = forms.CharField(required=True)
    permissions = forms.ModelMultipleChoiceField(None, widget=forms.CheckboxSelectMultiple(), label='', required=False)
    ldap_group = forms.CharField(required=False)
    priority = forms.IntegerField(help_text='Smallest value has highest priority in Group/Role assignment', required=True)
    comment = forms.CharField(
        widget=forms.Textarea,
        label="Optional comment",
        required=False
    )

    class Meta:
        model = DjangoGroup
        fields = ('name', 'permissions', 'ldap_group', 'priority', 'comment')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['permissions'].queryset = DjangoGroup.objects.filter(name='Superuser').first().permissions
        self.fields['permissions'].choices = DjangoGroup.objects.filter(name='Superuser').first().permissions.order_by('pk').values_list('pk', 'name')
        self.mapping = dict(DjangoGroup.objects.filter(name='Superuser').first().permissions.values_list('pk', 'codename'))

        if not get_middleware_module('common').has_extra_auth():
            self.fields.pop('ldap_group')
            self.fields.pop('priority')

        instance = kwargs.get('instance', None)
        if instance:
            self.initial['permissions'] = instance.permissions.values_list('pk', flat=True)
            self.initial['name'] = instance.name
            self.initial['ldap_group'] = instance.group.ldap_group

        if get_middleware_module('common').has_extra_auth():
            priority = Group.objects.aggregate(Max('priority'))['priority__max']
            if not instance:
                priority += 1
            self.fields['priority'].widget = forms.NumberInput(attrs={'max': priority, 'min': len(self.DEFAULT_GROUPS)})
            self.fields['priority'].initial = instance.group.priority if instance else priority

        # Put the comment field at the end of the self.fields ordered dict
        comment = self.fields.pop('comment')
        self.fields['comment'] = comment

        if instance:
            if instance.name in self.DEFAULT_GROUPS:
                for key in self.fields.keys():
                    if key not in ('ldap_group', 'comment'):
                        self.fields[key].disabled = True

    def save(self, commit=True):
        instance = super().save(commit=commit)

        created = False
        instance.permissions.add(*self.cleaned_data['permissions'])
        try:
            group = instance.group
            instance.name = self.cleaned_data['name']
            instance.group.ldap_group = self.cleaned_data.get('ldap_group', '')
        except AttributeError:
            group = Group.objects.create(
                group=instance,
                ldap_group=self.cleaned_data.get('ldap_group', '')
            )
            created = True

        if 'priority' in self.cleaned_data:
            new_priority = self.cleaned_data['priority']
            old_priority = self.instance.group.priority if not created else Group.objects.count() - 1
            max_priority = Group.objects.aggregate(Max('priority'))['priority__max']

            if new_priority <= max_priority:
                if old_priority > new_priority:
                    Group.objects.filter(
                        priority__gte=new_priority,
                        priority__lt=old_priority
                    ).update(priority=F('priority') + 1)
                elif old_priority < new_priority:
                    Group.objects.filter(
                        priority__lte=new_priority,
                        priority__gt=old_priority
                    ).update(priority=F('priority') - 1)

            group.priority = new_priority
            group.save()
        return instance


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput)
    persistent = forms.BooleanField(label="Remember this browser.", required=False)


TIMEZONES = ((x, x) for x in pytz.all_timezones)


class PasswordCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields.pop('username')


class UserSettingsForm(forms.ModelForm, CommentForm):
    TIMEZONES = ((x, x) for x in pytz.all_timezones)

    timezone = forms.ChoiceField(choices=TIMEZONES)
    groups = forms.ModelChoiceField(None, label='Role')
    tenants = forms.ModelMultipleChoiceField(None, widget=forms.CheckboxSelectMultiple(), label='', required=False)
    all_tenants = forms.BooleanField(required=False)
    no_tenant = forms.BooleanField(required=False)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'timezone', 'groups', 'is_active', 'no_tenant', 'all_tenants', 'tenants']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        instance = kwargs.get('instance', None)
        if not get_middleware_module('common').has_multitenant():
            self.fields.pop('tenants')
            self.fields.pop('no_tenant')
            self.fields.pop('all_tenants')
        else:
            self.fields['tenants'].queryset = get_middleware_module('common').get_tenants()

            if instance:
                self.fields['tenants'].initial = instance.sciriususer.get_tenants()
                self.fields['all_tenants'].initial = instance.sciriususer.has_all_tenants()
                self.fields['no_tenant'].initial = instance.sciriususer.has_no_tenant()

        self.fields['groups'].queryset = DjangoGroup.objects.order_by('name')
        if instance:
            # self.fields['groups'].initial does not work
            self.initial['groups'] = instance.groups.first().pk if instance.groups.count() > 0 else ''
            self.fields['timezone'].initial = instance.sciriususer.timezone

            if instance.sciriususer.is_from_ldap():
                self.fields['groups'].required = False
                # AUTH_LDAP_USER_ATTR_MAP => ldap user set first/last name and email
                for field in ('groups', 'first_name', 'last_name', 'email'):
                    self.fields[field].widget.attrs['readonly'] = True
                    self.fields[field].widget.attrs['disabled'] = True
                self.fields['groups'].help_text = 'Mapping ldap group to a Role is done on Role page for LDAP/AD users'

        else:
            self.fields['timezone'].initial = 'UTC'
            self.initial['groups'] = Group.objects.order_by('-priority').first()

    def clean(self):
        cleaned_data = super().clean()
        if 'groups' in cleaned_data:
            if cleaned_data['groups']:
                cleaned_data['groups'] = [cleaned_data['groups']]
            else:
                cleaned_data['groups'] = []
        return cleaned_data

    def save(self, commit=True):
        if not commit:
            raise NotImplementedError('This method does not support "commit=False"')

        instance = super().save()
        try:
            sciriususer = instance.sciriususer
            sciriususer.timezone = self.cleaned_data['timezone']
        except AttributeError:
            sciriususer = SciriusUser.objects.create(
                user=instance,
                timezone=self.cleaned_data['timezone'],
            )

        instance.save()
        get_middleware_module('common').update_scirius_user_class(instance, self.cleaned_data)
        return instance


class NormalUserSettingsForm(forms.ModelForm, CommentForm):
    TIMEZONES = ((x, x) for x in pytz.all_timezones)
    timezone = forms.ChoiceField(choices=TIMEZONES)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'timezone']


class PasswordForm(CommentForm):
    password = forms.CharField(label="New user password", widget=forms.PasswordInput)


class TokenForm(CommentForm):
    token = forms.CharField(label="Token", required=False)

    def __init__(self, *args, **kwargs):
        super(TokenForm, self).__init__(*args, **kwargs)
        self.fields['token'].widget.attrs['readonly'] = True

accounts/templates/accounts/accounts_list.html
{% extends "rules/base.html" %}
{% block sidebar %}
    {% for name, object in objects.items %}
        <div class="panel-heading">
            <h2 class="panel-title">{{ name }}{{ object.size|pluralize }}</h2>
        </div>
        <div class="panel-body">
            <ul>
                <li>{{ object.size }} object{{ object.size|pluralize }}</li>
            </ul>
        </div>
    {% endfor %}
    <div class="panel-heading">
        <h2 class="panel-title">Manage accounts</h2>
    </div>
    <div class="panel-body">
        <ul class="manage">
            <li>
                <a href="{% url 'list_users' %}">User list</a>
            </li>
            <li>
                <a href="{% url 'list_groups' %}">Role list</a>
            </li>
        </ul>
    </div>
    <div class="panel-heading">
        <h2 class="panel-title">Actions</h2>
    </div>
    <div class="panel-body">
        <ul class="action">
            <li>
                <a href="{% url 'add_user' %}">Add User</a>
            </li>
            <li>
                <a href="{% url 'add_group' %}">Add Role</a>
            </li>
            {% if extra_auth %}
                <li>
                    <a data-toggle="tooltip"
                       title="Set priority on Role/Group assignments"
                       href="{% url 'edit_priorities' %}">
                        Edit priorities
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
{% endblock sidebar %}
{% block content %}
    {% if objects %}
        {% for name, object in objects.items %}
            <div class="row">
                <h2 class="title">{{ name }}{{ object.size|pluralize }}</h2>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            {% load render_table from django_tables2 %}
                            {% render_table object.content %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        No object available.
    {% endif %}
{% endblock content %}

accounts/templates/accounts/edit.html
{% extends "rules/base.html" %}
{% load bootstrap3  %}
{% block sidebar %}
    <div class="panel-heading">
        <h2 class="panel-title">{{ action }}</h2>
    </div>
    <ul>
        {% if not is_from_ldap %}
            <li>
                <a href="{% url 'accounts_edit' 'password' %}">Change password</a>
            </li>
        {% endif %}
        <li>
            <a href="{% url 'accounts_edit' 'settings' %}">Edit settings</a>
        </li>
        <li>
            <a href="{% url 'accounts_edit' 'token' %}">Edit token</a>
        </li>
    </ul>
{% endblock sidebar %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                {% if edition %}
                    {% if form %}
                        <form action="{{ request.get_full_path }}" method="post" class="form">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            {% buttons %}
                            <button type="submit" class="btn btn-primary">
                                {% if action == 'User token' %}
                                    {% bootstrap_icon "refresh" %} Regenerate
                                {% else %}
                                    {% bootstrap_icon "ok" %} Valid
                                {% endif %}
                            </button>
                        {% endbuttons %}
                    </form>
                {% endif %}
            {% else %}
                <h2>Logged in as {{ user.username }}</h2>
                <ul class="list-group">
                    <li class="list-group-item">
                        <strong>First name:</strong>
                        <span class="pull-right">{{ user.first_name }}</span>
                    </li>
                    <li class="list-group-item">
                        <strong>Last name:</strong>
                        <span class="pull-right">{{ user.last_name }}</span>
                    </li>
                    <li class="list-group-item">
                        <strong>Email:</strong>
                        <span class="pull-right">{{ user.email }}</span>
                    </li>
                    {% if user.sciriususer %}
                        <li class="list-group-item">
                            <strong>Timezone:</strong>
                            <span class="pull-right">{{ user.sciriususer.timezone }}</span>
                        </li>
                    {% endif %}
                    <li class="list-group-item">
                        <strong>Active:</strong>
                        <span class="pull-right">{{ user.is_active }}</span>
                    </li>
                    <li class="list-group-item">
                        <strong>Role:</strong>
                        <span class="pull-right">
                            {% with user.groups.all|first as group %}{{ group.name }}{% endwith %}
                        </span>
                    </li>
                    {% if tenants or all_tenants or no_tenant %}
                        <li class="list-group-item">
                            <strong>No tenant:</strong>
                            <span class="pull-right">{{ no_tenant }}</span>
                        </li>
                        <li class="list-group-item">
                            <strong>All tenants:</strong>
                            <span class="pull-right">{{ all_tenants }}</span>
                        </li>
                        <li class="list-group-item">
                            <strong>Tenants:</strong>
                            {% if tenants %}
                                {% for tenant in tenants %}
                                    <div style="margin-right:0;" class="row">
                                        <span class="pull-right">{{ tenant }}</span>
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </li>
                    {% endif %}
                </ul>
                <div class="row">
                    <p>
                        Choose action in the left menu.
                    </p>
                </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/login.html
{% load staticfiles %}
{% load bootstrap3  %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>
            {% block title %}Scirius Security Platform{% endblock %}
        </title>
        <link rel="stylesheet" href="{% static 'rules/bootstrap.min.css' %}" />
        <link rel="stylesheet"
              type="text/css"
              href="{% static 'rules/static.css' %}"/>
        <link rel="shortcut icon" href="{% static 'rules/favicon.ico' %}" />
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    {% if error %}<div class="alert alert-danger">{{ error }}</div>{% endif %}
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    {% if not in_selks %}
                        <img class="center-block"
                             id="sciriuslogo"
                             src="{% static 'rules/stamus_logo_full.png' %}"/>
                    {% else %}
                        <img class="img-circle center center-block"
                             id="sciriuslogo"
                             src="{% static 'rules/scirius.jpg' %}"/>
                    {% endif %}
                </div>
            </div>
            <div class="row row-eq-height">
                <div class="col-md-3 col-xs-12"></div>
                <div class="col-md-4 col-xs-12">
                    <div class="jumbotron fill" id="logininfo">
                        <h2>Scirius Security Platform</h2>
                        <p class="lead">
                            Scirius Security Platform is an advanced network detection and response (NDR) solution
                            that mitigates risk by exposing threats to critical assets and empowering rapid response.
                        </p>
                        <hr class="m-y-2">
                        <p class="minor">
                            Scirius Security Platform is developed by Stamus Networks and provides:
                        </p>
                        <ul>
                            <li>
                                <p class="minor">
                                    Comprehensive network inspection for complete visibility into network activity and threat events
                                </p>
                            </li>
                            <li>
                                <p class="minor">
                                    Guided threat hunting for proactive network defence and incident investigation using enriched event data
                                </p>
                            </li>
                            <li>
                                <p class="minor">
                                    Automated detection and notification of acute and urgent threats to assets, tracked by stage on the cyber kill chain
                                </p>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-2 col-xs-12">
                    <div class="panel panel-default fill" id="login">
                        <div class="panel-heading">
                            <h2 class="panel-title">Login to Scirius</h2>
                        </div>
                        <div>
                            <form action="{{ request.get_full_path }}" method="post" class="form">
                                {% csrf_token %}
                                {% bootstrap_form form %}
                                {% buttons %}
                                    <button type="submit" class="btn btn-primary">{% bootstrap_icon "ok" %} Login</button>
                                {% endbuttons %}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- row -->
            <hr>
            <ul class="list-inline text-center">
                <li>
                    <a href="https://www.stamus-networks.com"><img src="{% static 'rules/stamus.png' %}"/></a>
                <li>
                        <!-- <li><a href="/">Stamus Networks</a><li> -->
                <li>
                    <a href="https://www.stamus-networks.com/scirius-open-source">Scirius Community Edition</a>
                </li>
                <li>
                    <a href="https://www.stamus-networks.com/scirius-platform">Scirius Security Platform</a>
                </li>
                <li><li>
            </ul>
        </div>
        <!-- container-fluid -->
    </body>
</html>

accounts/templates/accounts/user.html
{% extends "rules/base.html" %}
{% load bootstrap3  %}
{% block sidebar %}
    <div class="panel-heading">
        <h2 class="panel-title">Manage users</h2>
    </div>
    <ul>
        <li>
            <a href="{% url 'list_accounts' %}">Accounts list</a>
        </li>
        <li>
            <a href="{% url 'list_users' %}">User list</a>
        </li>
        <li>
            <a href="{% url 'list_groups' %}">Role list</a>
        </li>
        {% if extra_auth %}
            <li>
                <a data-toggle="tooltip"
                   title="Set priority on Role/Group assignments"
                   href="{% url 'edit_priorities' %}">
                    Edit priorities
                </a>
            </li>
        {% endif %}
    </ul>
    {% if current_action != 'Add user' %}
        <div class="panel-heading">
            <h2 class="panel-title">Actions</h2>
        </div>
        <ul>
            {% if 'Edit password' not in current_action and not is_from_ldap %}
                <li>
                    <a href="{% url 'edit_password' user.pk %}">Change user password</a>
                </li>
            {% endif %}
            <li>
                <a href="#" onclick="del_user();">Delete user</a>
            </li>
        </ul>
        <script language="JavaScript">
function del_user() {
    let username = {{ username|safe }};
    confirmModal({
        title: `Delete user "${username}"`,
        msg: "Do you want to delete this user ?",
        comment: true,
        cb: function() {
            let comment = $("#generic-modal-comment").val();
            $.ajax({
                type: 'POST',
                data: {'comment': comment},
                url: "{% url 'delete_user' user.pk %}",
                success: function(data) {
                    if (data.redirect) {
                        window.location.href = data.redirect;
                    }

                    if (data.error) {
                        $('#error').parent('.alert').show();
                        $('#error').parent('.alert').text(data.error);
                    }
                }
            });
        }
    });
    return false;
}
        </script>
    {% endif %}
{% endblock sidebar %}
{% block content %}
    <div class="container-fluid">
        <h2>{{ current_action }}</h2>
        <div class="row">
            <div class="col-md-6">
                <form action="{{ request.get_full_path }}" method="post" class="form">
                    {% csrf_token %}
                    {% if 'Edit password' in current_action %}
                        {% bootstrap_form form %}
                    {% else %}
                        {% bootstrap_field form.username %}
                        {% if current_action == 'Add user' %}
                            {% bootstrap_form password_form %}
                        {% endif %}
                        {% bootstrap_field form.first_name %}
                        {% bootstrap_field form.last_name %}
                        {% bootstrap_field form.email %}
                        {% if user.sciriususer %}
                            {% bootstrap_field form.timezone %}
                        {% endif %}
                        {% bootstrap_field form.groups %}
                        {% bootstrap_field form.is_active %}
                        {% if form.no_tenant or form.all_tenants or form.tenants %}
                            <label class="control-label" for="id_tenants">Tenants</label>
                            {% bootstrap_field form.no_tenant %}
                            {% bootstrap_field form.all_tenants %}
                            {% bootstrap_field form.tenants %}
                        {% endif %}
                    {% endif %}
                    {% buttons %}
                        <button type="submit" class="btn btn-primary">
                            {% bootstrap_icon "ok" %}
                            {% if current_action == 'Add user' %}
                                Add
                            {% else %}
                                Submit
                            {% endif %}
                        </button>
                    {% endbuttons %}
                </form>
            </div>
        </div>
    </div>
    {% if form.no_tenant or form.all_tenants or form.tenants %}
    <script language="JavaScript">
function click_all_tenants() {
    if ($("#id_all_tenants").is(":checked")) {
        $('#id_tenants').parents('.form-group').hide(duration=200);
    } else {
        $('#id_tenants').parents('div')[0].style['padding-left'] = '5%';
        $('#id_tenants').parents('.form-group').show(duration=200);
    }
}
$('document').ready(function() {
    $("#id_all_tenants").change(click_all_tenants);
    click_all_tenants();
});
    </script>
    {% endif %}
{% endblock %}